GET http://localhost:3000/api
Authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQ5NTE2MjU4LCJlbWFpbCI6IjQ5NTE2MjU4QHFxLmNvbSIsInZhbHVlIjoiNDk1MTYyNThAcXEuY29tIiwiaWF0IjoxNzExNjgyMjcxLCJleHAiOjE3MTE2ODU4NzF9.DucxAuRBWNtof67Ow1hVKSe3ZV9PJZNo_xqztP-CYblH0A5s-ZOB5YN-N4gJsnngu2fgL3UgX7m8JpIpicgeBw


###
GET http://localhost:3000/api/worker
Authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQ5NTE2MjU4LCJlbWFpbCI6IjQ5NTE2MjU4QHFxLmNvbSIsInZhbHVlIjoiNDk1MTYyNThAcXEuY29tIiwiaWF0IjoxNzExNjgyMjcxLCJleHAiOjE3MTE2ODU4NzF9.DucxAuRBWNtof67Ow1hVKSe3ZV9PJZNo_xqztP-CYblH0A5s-ZOB5YN-N4gJsnngu2fgL3UgX7m8JpIpicgeBw